Add templating
pitzzahh/test-pdf-gen pull request #5
Opened 2024-07-11 09:27 UTC by ChristineJoyE

2024-07-15 06:25 UTC, pitzzahh requested changes

2024-07-15 06:25 UTC, pitzzahh commented on src/lib/server/pdf/index.ts
> +type Alignment = 'center' | 'right'
Move types to type.ts
@Paotatoo
@Tinitine

2024-07-15 06:25 UTC, pitzzahh commented on src/lib/assets/icons/mail.png
Add padding sa mail icon kasi dikit masyado sa edges 
@Tinitine

2024-07-15 06:25 UTC, pitzzahh commented on src/lib/server/pdf/index.ts
> +type TableData = {
Also mote to types.ts
@Paotatoo

2024-07-15 06:25 UTC, pitzzahh commented on src/lib/server/pdf/index.ts
>  export const generatePDF = async (
Add another prop for the signing officials.

2024-07-15 06:25 UTC, pitzzahh commented on src/lib/server/pdf/index.ts
> +type Alignment = 'center' | 'right'
Also move to type.ts

2024-07-15 06:25 UTC, pitzzahh commented on src/routes/api/pdf/[record]/+server.ts
>  export const GET = async ({ params }) => {
should be a POST request

[Guide](https://learn.svelte.dev/tutorial/post-handlers)

2024-07-15 06:25 UTC, pitzzahh commented on src/lib/server/pdf/index.ts
> +type Alignment = 'center' | 'right'
dipa na move pati su iba

2024-07-15 06:25 UTC, pitzzahh commented on src/routes/api/pdf/[record]/+server.ts
> +	const pdf = await generatePDF(doc,info,veriBy, [] ,metadata);
Add sample data

2024-08-05 23:39 UTC, Tinitine commented on src/lib/assets/icons/mail.png
Okay po boss

2024-08-12 05:15 UTC, pitzzahh approved these changes

2024-08-12 05:15 UTC, merged